=== nguyentthomas/WebServicesDevelopment/build/web/TextbooksLists.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.uts.edu.au/31284/wsd-diary"
    xmlns="http://www.uts.edu.au/31284/wsd-diary"
    elementFormDefault="qualified">


    <xs:simpleType name="title">
        <xs:restriction base="xs:string">
            
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="author">
        <xs:restriction base="xs:string">
            
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="category">
        <xs:restriction base="xs:string">
            
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="number">
        <xs:restriction base="xs:string">
            <xs:pattern value="."/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="lister">
        <xs:restriction base="xs:string">
            <xs:pattern value="([A-Z][a-z]+)(([\s])([A-Z][a-z]+))*"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="abstract">
        <xs:restriction base="xs:string">
            
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="ISBN">
        <xs:restriction base="xs:string">
            
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="edition">
        <xs:restriction base="xs:string">
            
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="yearofPublication">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-z][0-9]{4}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="publisher">
        <xs:restriction base="xs:string">
            
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="condition">
        <xs:restriction base="xs:string">
            
        </xs:restriction>
    </xs:simpleType>





<xs:element name="TextbooksLists">

    <xs:complexType mixed="true">
        <xs:sequence>
            <xs:element name="Textbooks" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType mixed="true">
                    <xs:sequence>
                        <xs:element name="title" type="title"/>
                        <xs:element name="author" type="author"/>
                        <xs:element name="category" type="category"/>
                        <xs:element name="number" type="number"/>

                        <xs:element name="thisbooklist" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType mixed="true">
                                <xs:sequence>
                                    <xs:element name="Textbook" minOccurs="0" maxOccurs="unbounded">
                                        <xs:complexType mixed="true">
                                            <xs:sequence>
                                                <xs:element name="lister" type="xs:string"/>
                                                <xs:element name="abstract" type="xs:string"/>
                                                <xs:element name="publicationData" minOccurs="0" maxOccurs="unbounded">
                                                    <xs:complexType mixed="true">
                                                        <xs:sequence>
                                                            <xs:element name="ISBN" type="ISBN"/>
                                                            <xs:element name="edition" type="edition"/>
                                                            <xs:element name="yearofPublication" type="yearofPublication"/>
                                                            <xs:element name="publisher" type="publisher"/>
                                                        </xs:sequence>
                                                    </xs:complexType>
                                                </xs:element>
                                                <xs:element name="condition" type="condition"/>

                                            </xs:sequence>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>

                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>


</xs:element>
</xs:schema>

=== nguyentthomas/WebServicesDevelopment/web/TextbooksLists.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="TextbooksLists.xsl"?> 
<!-- removed from TextbooksLists tag xmlns="http://www.uts.edu.au/31284/wsd-diary"-->
<TextbooksLists xmlns="http://www.uts.edu.au/31284/wsd-diary"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:schemaLocation="http://www.uts.edu.au/31284/wsd-diary TextbooksLists.xsd">
    <Textbooks>
        <title>JSP and XML: integrating XML and web services in your JSP application</title>
        <author>Casey Kochmer and Erica Frandsen</author>
        <category>JavaServer pages</category>
        <number>4</number>
        <thisbooklist>
            <Textbook>
                <lister>Thomas Qi</lister>
                <abstract>
                </abstract>
                <publicationData>
                    <ISBN>0672323540</ISBN>
                    <edition>First Edition</edition>
                    <yearofPublication>c2002</yearofPublication>
                    <publisher>Boston: Addison-Wesley</publisher>
                </publicationData>
                <condition>Poor</condition>
            </Textbook>
            <Textbook>
                <lister>Pengfei Qi</lister>
                <abstract>
                </abstract>
                <publicationData>
                    <ISBN>0672323540</ISBN>
                    <edition>First Edition</edition>
                    <yearofPublication>c2002</yearofPublication>
                    <publisher>Boston: Addison-Wesley</publisher>
                </publicationData>
                <condition>Fair</condition>
            </Textbook>
            <Textbook>
                <lister>Henry Qi</lister>
                <abstract>
                </abstract>
                <publicationData>
                    <ISBN>0672323540</ISBN>
                    <edition>Second Edition</edition>
                    <yearofPublication>c2008</yearofPublication>
                    <publisher>Boston: Addison-Wesley</publisher>
                </publicationData>
                <condition>Good</condition>
            </Textbook>
            <Textbook>
                <lister>Thomas Qi</lister>
                <abstract>
                </abstract>
                <publicationData>
                    <ISBN>0672323540</ISBN>
                    <edition>Forth Edition</edition>
                    <yearofPublication>c2018</yearofPublication>
                    <publisher>Boston: Addison-Wesley</publisher>
                </publicationData>
                <condition>New</condition>
            </Textbook>
        </thisbooklist>
    </Textbooks>

    <Textbooks>
        <title>Java and XML</title>
        <author>Brett D. McLaughlin and Justin Edelson</author>
        <category>Web publishing</category>
        <number>3</number>
        <thisbooklist>
            <Textbook>
                <lister>Henry Qi</lister>
                <abstract>
                </abstract>
                <publicationData>
                    <ISBN>0672323540</ISBN>
                    <edition>First Edition</edition>
                    <yearofPublication>c2002</yearofPublication>
                    <publisher>Boston: Addison-Wesley</publisher>
                </publicationData>
                <condition>New</condition>
            </Textbook>
            <Textbook>
                <lister>Henry Qi</lister>
                <abstract>
                </abstract>
                <publicationData>
                    <ISBN>0672323540</ISBN>
                    <edition>First Edition</edition>
                    <yearofPublication>c2002</yearofPublication>
                    <publisher>Boston: Addison-Wesley</publisher>
                </publicationData>
                <condition>Poor</condition>
            </Textbook>
            <Textbook>
                <lister>Thomas Qi</lister>
                <abstract>
                </abstract>
                <publicationData>
                    <ISBN>0672323540</ISBN>
                    <edition>First Edition</edition>
                    <yearofPublication>c2002</yearofPublication>
                    <publisher>Boston: Addison-Wesley</publisher>
                </publicationData>
                <condition>Poor</condition>
            </Textbook>
        </thisbooklist>
    </Textbooks>

    <Textbooks>
        <title>Building Web services with Java : making sense of XML, SOAP, WSDL, and UDDI</title>
        <author> Steve Graham ... [et al.]</author>
        <category>Application software -- Development.</category>
        <number>2</number>
        <thisbooklist>
            <Textbook>
                <lister>Thomas Qi</lister>
                <abstract>
                </abstract>
                <publicationData>
                    <ISBN>0672323540</ISBN>
                    <edition>First Edition</edition>
                    <yearofPublication>c2002</yearofPublication>
                    <publisher>Boston: Addison-Wesley</publisher>
                </publicationData>
                <condition>Poor</condition>
            </Textbook>
            <Textbook>
                <lister>Pengfei Qi</lister>
                <abstract>
                </abstract>
                <publicationData>
                    <ISBN>0672323540</ISBN>
                    <edition>First Edition</edition>
                    <yearofPublication>c2002</yearofPublication>
                    <publisher>Boston: Addison-Wesley</publisher>
                </publicationData>
                <condition>Fair</condition>
            </Textbook>
        </thisbooklist>
    </Textbooks>

    <Textbooks>
        <title>Routing and switching essentials companion guide</title>
        <author>Cisco Networking Academy</author>
        <category>Telecommunication -- Switching systems</category>
        <number>1</number>
        <thisbooklist>
            <Textbook>
                <lister>Thomas Qi</lister>
                <abstract>
                </abstract>
                <publicationData>
                    <ISBN>0672323540</ISBN>
                    <edition>First Edition</edition>
                    <yearofPublication>c2002</yearofPublication>
                    <publisher>Boston: Addison-Wesley</publisher>
                </publicationData>
                <condition>Poor</condition>
            </Textbook>
        </thisbooklist>
    </Textbooks>

</TextbooksLists>
