=== nguyentthomas/WebServicesDevelopment/build/web/WEB-INF/Listers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.uts.edu.au/31284/wsd-diary"
    xmlns="http://www.uts.edu.au/31284/wsd-diary"
    elementFormDefault="qualified">

    
    <xs:simpleType name="email">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}"/>
        </xs:restriction>    
    </xs:simpleType>
    
    <xs:simpleType name="userName">
        <xs:restriction base="xs:string">
            <xs:pattern value="([A-Z][a-z]+[\s])+[A-Z][a-z]*"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="date">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{1,2}/\d{1,2}/\d{1,4}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="password">
        <xs:restriction base="xs:string">
            <xs:pattern value=".{8}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:element name="listers">

        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element name="lister" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType mixed="true">
                        <xs:sequence>
                            <xs:element name="email" type="email"/>
                            <xs:element name="userName" type="userName"/>
                            <xs:element name="password" type="password"/>
                            <xs:element name="DOB" type="date"/>
                                      
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                        
                    
                
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== nguyentthomas/WebServicesDevelopment/build/web/WEB-INF/Listers.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- removed from listers tag xmlns="http://www.uts.edu.au/31284/wsd-diary"-->
<listers xmlns="http://www.uts.edu.au/31284/wsd-diary"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.uts.edu.au/31284/wsd-diary Listers.xsd">
    <lister>
        <email>thomas.nguyen@hotmail.com</email>
        <userName>Thomas Qi</userName>
        <password>thom2123</password>
        <DOB>1/1/1999</DOB>
    </lister>
    <lister>
        <email>henry.dinher2@hotmail.com</email>
        <userName>Henry Qi</userName>
        <password>henr1234</password>
        <DOB>1/1/1999</DOB>
    </lister>
    <lister>
        <email>Pengfei145@hotmail.com</email>
        <userName>Pengfei Qi</userName>
        <password>peng1234</password>
        <DOB>1/1/1999</DOB>
    </lister>
    <lister>
        <email>henry90@gmail.com</email>
        <userName>Ddinhers Qi</userName>
        <password>henr1234</password>
        <DOB>1/1/1999</DOB>
    </lister>
</listers>
